### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by pepperjack09** [zakkarry/retraktarr#10]
Successfully created API OAuth with Trakt:

retraktarr v1.1.2
Validating Configuration File: C:\Users\user\.config\retraktarr.conf

Authorization Code:  eec3b49971b1911e#########d4fcd5e3dadaa5f5b38412d117d28
Access Token:  3a47e83dcc20c##############759b06703ee30079a7f7ebfe533a912f4
Refresh Token:  622929698cea7a##############a7b3c71951a738d65cf5bb
Your configuration file was successfully updated with your access/refresh token.

However, when I run retraktarr -r, it returns:

[Radarr]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\retraktarr.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\retraktarr\retraktarr.py", line 174, in main
    trakt_api.add_to_list(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\retraktarr\api\trakt.py", line 500, in add_to_list
    added_items = response.json()["added"][media_type.lower()]
                  ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by pepperjack09** [comment]
user error, Radarr's Basic Authentication was getting in the way. Was originally executing on a PC outside of my local network over VPN.

Works great now on local network, thanks for this!!

**Comment by zakkarry** [comment]
Appreciate your letting me know it was not a program error, if you have any other issues or think of any features that could be added be sure to let me know.

Thanks for the support and kind words.
